import type { HealthReport } from '../../../application/use-cases/check-health.js';
import type { crearActualizarLocal } from '../../../application/use-cases/actualizar-local.js';
import type { crearObtenerUrlFotoUsuario, crearQuitarFotoPerfil, crearRegistrarFotoPerfil, crearSolicitarUrlSubidaPerfil } from '../../../application/use-cases/foto-perfil.js';
import type { crearObtenerUrlFoto, crearQuitarFotoLocal, crearRegistrarFotoLocal, crearSolicitarUrlSubida } from '../../../application/use-cases/archivos.js';
import type { crearActualizarCamion, crearCrearCamion, crearListarCamiones } from '../../../application/use-cases/camiones.js';
import type { crearExportarLocales } from '../../../application/use-cases/exportar-locales.js';
import type { crearBuscarPinesPendientes, crearEstadoBusquedaPines } from '../../../application/use-cases/buscar-pines.js';
import type { crearFijarPinDesdeEnlace } from '../../../application/use-cases/pin-desde-enlace.js';
import type { crearAplicarPlanilla, crearObtenerPlanilla } from '../../../application/use-cases/planilla.js';
import type { crearActualizarVendedor, crearCrearVendedor, crearListarVendedores } from '../../../application/use-cases/vendedores.js';
import type { crearActualizarFactura, crearListarFacturas, crearRegistrarFactura } from '../../../application/use-cases/facturas.js';
import type { crearGuardarConfigEmpresa, crearObtenerConfigEmpresa } from '../../../application/use-cases/config-empresa.js';
import type { crearServiciosDeRuta } from '../../../application/use-cases/rutas.js';
import type { crearGuardarHorario, crearObtenerHorario } from '../../../application/use-cases/horarios.js';
import type { VerAnalitica } from '../../../application/use-cases/analitica.js';
import type { AnalizarAprendizaje } from '../../../application/use-cases/analizar-aprendizaje.js';
import type { crearReportarLocal, crearResolverReporteLocal, crearVerReportes } from '../../../application/use-cases/reportes-local.js';
import type { crearVerificarPin } from '../../../application/use-cases/pin-verificado.js';
import type { crearRevisarPines } from '../../../application/use-cases/revisar-pines.js';
import type { RegistrarPosiciones } from '../../../application/use-cases/seguimiento.js';
import type { crearIniciarJornada, crearMiJornada, crearTerminarJornada } from '../../../application/use-cases/jornada.js';
import type { crearRegistrarEvento } from '../../../application/use-cases/entregas.js';
import type { crearAutenticarUsuario } from '../../../application/use-cases/autenticar-usuario.js';
import type { crearBuscarClientes } from '../../../application/use-cases/buscar-clientes.js';
import type { crearCrearClienteNuevo } from '../../../application/use-cases/crear-cliente-nuevo.js';
import type { crearCrearUsuario } from '../../../application/use-cases/crear-usuario.js';
import type { crearCambiarEditorUsuario, crearCambiarEstadoUsuario, crearListarUsuarios, crearResetearPin } from '../../../application/use-cases/gestionar-usuarios.js';
import type { crearFotosParaRevision, crearReportarFoto, crearResolverReporteFoto, crearVerificarFoto } from '../../../application/use-cases/fotos-revision.js';
import type { crearImportarClientes } from '../../../application/use-cases/importar-clientes.js';
import type { crearIniciarSesion } from '../../../application/use-cases/iniciar-sesion.js';
import type { crearCorregirCliente, crearEliminarLocal } from '../../../application/use-cases/corregir-clientes.js';
import type { crearListarLocales, crearResumenComunas } from '../../../application/use-cases/listar-locales.js';
import type { crearObtenerLocal } from '../../../application/use-cases/obtener-local.js';
import type { crearListarPropuestasPin, crearResolverPropuestaPin } from '../../../application/use-cases/pines.js';
import type { crearRefrescarSesion } from '../../../application/use-cases/refrescar-sesion.js';

/** Todo lo que el adaptador HTTP necesita del resto de la aplicación; `main` lo arma y lo inyecta. */
export type CasosDeUso = {
  readonly checkHealth: () => Promise<HealthReport>;
  readonly autenticar: ReturnType<typeof crearAutenticarUsuario>;
  readonly iniciarSesion: ReturnType<typeof crearIniciarSesion>;
  readonly refrescarSesion: ReturnType<typeof crearRefrescarSesion>;
  readonly crearUsuario: ReturnType<typeof crearCrearUsuario>;
  readonly listarUsuarios: ReturnType<typeof crearListarUsuarios>;
  readonly resetearPin: ReturnType<typeof crearResetearPin>;
  readonly cambiarEstadoUsuario: ReturnType<typeof crearCambiarEstadoUsuario>;
  readonly cambiarEditorUsuario: ReturnType<typeof crearCambiarEditorUsuario>;
  readonly solicitarUrlSubidaPerfil: ReturnType<typeof crearSolicitarUrlSubidaPerfil>;
  readonly registrarFotoPerfil: ReturnType<typeof crearRegistrarFotoPerfil>;
  readonly quitarFotoPerfil: ReturnType<typeof crearQuitarFotoPerfil>;
  readonly obtenerUrlFotoUsuario: ReturnType<typeof crearObtenerUrlFotoUsuario>;
  readonly buscarClientes: ReturnType<typeof crearBuscarClientes>;
  readonly crearClienteNuevo: ReturnType<typeof crearCrearClienteNuevo>;
  readonly importarClientes: ReturnType<typeof crearImportarClientes>;
  readonly obtenerLocal: ReturnType<typeof crearObtenerLocal>;
  readonly actualizarLocal: ReturnType<typeof crearActualizarLocal>;
  readonly listarPropuestasPin: ReturnType<typeof crearListarPropuestasPin>;
  readonly resolverPropuestaPin: ReturnType<typeof crearResolverPropuestaPin>;
  readonly solicitarUrlSubida: ReturnType<typeof crearSolicitarUrlSubida>;
  readonly registrarFotoLocal: ReturnType<typeof crearRegistrarFotoLocal>;
  readonly quitarFotoLocal: ReturnType<typeof crearQuitarFotoLocal>;
  readonly corregirCliente: ReturnType<typeof crearCorregirCliente>;
  readonly listarLocales: ReturnType<typeof crearListarLocales>;
  readonly resumenComunas: ReturnType<typeof crearResumenComunas>;
  readonly eliminarLocal: ReturnType<typeof crearEliminarLocal>;
  readonly reportarFoto: ReturnType<typeof crearReportarFoto>;
  readonly reportarLocal: ReturnType<typeof crearReportarLocal>;
  readonly verReportes: ReturnType<typeof crearVerReportes>;
  readonly resolverReporteLocal: ReturnType<typeof crearResolverReporteLocal>;
  readonly fotosParaRevision: ReturnType<typeof crearFotosParaRevision>;
  readonly verificarFoto: ReturnType<typeof crearVerificarFoto>;
  readonly verificarPin: ReturnType<typeof crearVerificarPin>;
  readonly revisarPines: ReturnType<typeof crearRevisarPines>;
  readonly resolverReporteFoto: ReturnType<typeof crearResolverReporteFoto>;
  readonly exportarLocales: ReturnType<typeof crearExportarLocales>;
  readonly obtenerUrlFoto: ReturnType<typeof crearObtenerUrlFoto>;
  readonly listarCamiones: ReturnType<typeof crearListarCamiones>;
  readonly crearCamion: ReturnType<typeof crearCrearCamion>;
  readonly actualizarCamion: ReturnType<typeof crearActualizarCamion>;
  readonly buscarPinesPendientes: ReturnType<typeof crearBuscarPinesPendientes>;
  readonly estadoBusquedaPines: ReturnType<typeof crearEstadoBusquedaPines>;
  readonly fijarPinDesdeEnlace: ReturnType<typeof crearFijarPinDesdeEnlace>;
  readonly listarVendedores: ReturnType<typeof crearListarVendedores>;
  readonly crearVendedor: ReturnType<typeof crearCrearVendedor>;
  readonly actualizarVendedor: ReturnType<typeof crearActualizarVendedor>;
  readonly aplicarPlanilla: ReturnType<typeof crearAplicarPlanilla>;
  readonly obtenerPlanilla: ReturnType<typeof crearObtenerPlanilla>;
  readonly registrarFactura: ReturnType<typeof crearRegistrarFactura>;
  readonly listarFacturas: ReturnType<typeof crearListarFacturas>;
  readonly actualizarFactura: ReturnType<typeof crearActualizarFactura>;
  readonly verRuta: ReturnType<typeof crearServiciosDeRuta>['ver'];
  readonly planificarRuta: ReturnType<typeof crearServiciosDeRuta>['planificar'];
  readonly operarRuta: ReturnType<typeof crearServiciosDeRuta>['operar'];
  readonly miJornada: ReturnType<typeof crearMiJornada>;
  readonly iniciarJornada: ReturnType<typeof crearIniciarJornada>;
  readonly terminarJornada: ReturnType<typeof crearTerminarJornada>;
  readonly registrarEvento: ReturnType<typeof crearRegistrarEvento>;
  readonly registrarPosiciones: RegistrarPosiciones;
  readonly verAnalitica: VerAnalitica;
  readonly ejecutarAnalisis: AnalizarAprendizaje;
  readonly obtenerHorario: ReturnType<typeof crearObtenerHorario>;
  readonly guardarHorario: ReturnType<typeof crearGuardarHorario>;
  readonly obtenerConfigEmpresa: ReturnType<typeof crearObtenerConfigEmpresa>;
  readonly guardarConfigEmpresa: ReturnType<typeof crearGuardarConfigEmpresa>;
};
